# Server Configuration
[server]
api_host = "127.0.0.1"
api_port = 8080
frontend_host = "127.0.0.1"
frontend_port = 8081

# Frontend Paths
[frontend]
dir = "frontend"
static_dir = "static"
templates_dir = "templates"
index_html = "index.html"

# Exchange API URLs
[exchange.binance]
ws_url = "wss://stream.binance.com:9443/ws/btcusdt@depth"
rest_url = "https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=1000"

[exchange.kraken]
url = "https://api.kraken.com/0/public/Depth?pair=XBTUSDT"

[exchange.huobi]
url = "https://api.huobi.pro/market/depth"

# Exchange Configuration
[exchange.config]
initial_reconnect_delay = 1 # 1 second
ping_interval = 30 # 30 seconds
max_reconnect_delay = 300 # 5 minutes
ping_retry_count = 3 # 3 retries

# Price Weighting Configuration
[price_weighting]
# Controls how quickly older prices lose influence (in seconds)
# Larger value = slower decay, smaller value = faster decay
# Examples with decay_factor = 300:
# - Current price: 100% influence
# - 5-minute-old price: ~37% influence
# - 10-minute-old price: ~14% influence
# - 20-minute-old price: ~2% influence
decay_factor = 300 # 5 minutes